In [1]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\hp\anaconda3\lib\site-packages (8.0.33)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in c:\users\hp\anaconda3\lib\site-packages (from mysql-connector-python) (3.20.3)

In [2]:
import mysql.connector

In [6]:
mydb=mysql.connector.connect(
     host="localhost",
     user="root",
     password="",
     database="EMS"
)

def search(Id):
    cursor = mydb.cursor()
    query = "SELECT * FROM EMPLOYEE WHERE EMP_ID LIKE '%{}'".format(Id)
    cursor.execute(query)
    result=cursor.fetchall()
    if result:
        return True
    else:
        return False
    cursor.close()

def add_Emp(Id,name,salary,department,email):
    cursor = mydb.cursor()
    query = "INSERT INTO EMPLOYEE VALUES(%s,%s,%s,%s,%s)"
    values =(Id,name,salary,department,email)
    cursor.execute(query,values)
    mydb.commit()
    print("Success!!!\n")
    cursor.close()

def update_Emp(Id,name,salary,department,email):
    cursor = mydb.cursor()
    query = "UPDATE EMPLOYEE SET EMP_NAME=%s,EMP_SALARY=%s,EMP_DEPT=%s,EMAIL=%s WHERE EMP_ID=%s"
    values = (name,salary,department,email,Id)
    cursor.execute(query,values)
    mydb.commit()
    print("Successfully Updated!!\n")
    cursor.close()

def delete_Emp(Id):
    cursor = mydb.cursor()
    query = "DELETE FROM EMPLOYEE WHERE EMP_ID LIKE '%{}'".format(Id)
    cursor.execute(query)
    mydb.commit()
    print("Deleted..")
    cursor.close()
    
def listall():
    cursor = mydb.cursor()
    query = "SELECT * FROM EMPLOYEE"
    cursor.execute(query)
    result = cursor.fetchall()
    if result:
        print("Employee Details : ")
        print("-------------------")
        for row in result:
            print("Employee Id : ",row[0])
            print("Employee Name : ",row[1])
            print("Salary : ",row[2])
            print("Department : ",row[3])
            print("Email : ",row[4])
            print("---------------------")
    else:
        print("Empty!!")
    cursor.close()
    
def sortDept():
    cursor = mydb.cursor()
    query = "SELECT * FROM EMPLOYEE ORDER BY EMP_DEPT"
    cursor.execute(query)
    result = cursor.fetchall()
    if result:
        print("Employee Details : ")
        print("-------------------")
        for row in result:
            print("Employee Id : ",row[0])
            print("Employee Name : ",row[1])
            print("Salary : ",row[2])
            print("Department : ",row[3])
            print("Email : ",row[4])
            print("---------------------")
    else:
        print("Empty!!")
    cursor.close()
    
def sortSalary():
    cursor = mydb.cursor()
    query = "SELECT * FROM EMPLOYEE ORDER BY EMP_SALARY"
    cursor.execute(query)
    result = cursor.fetchall()
    if result:
        print("Employee Details : ")
        print("-------------------")
        for row in result:
            print("Employee Id : ",row[0])
            print("Employee Name : ",row[1])
            print("Salary : ",row[2])
            print("Department : ",row[3])
            print("Email : ",row[4])
            print("---------------------")
    else:
        print("Empty!!")
    cursor.close()
    
def filterDept(dept):
    cursor = mydb.cursor()
    query = "SELECT * FROM EMPLOYEE WHERE EMP_DEPT LIKE '%{}'".format(dept)
    cursor.execute(query)
    result = cursor.fetchall()
    if result:
        print("Employee Details : ")
        print("-------------------")
        for row in result:
            print("Employee Id : ",row[0])
            print("Employee Name : ",row[1])
            print("Salary : ",row[2])
            print("Department : ",row[3])
            print("Email : ",row[4])
            print("---------------------")
    else:
        print("Empty!!")
    cursor.close()
    
def  filterSalary(mini,maxi):
    cursor = mydb.cursor()
    query = "SELECT * FROM EMPLOYEE WHERE EMP_SALARY BETWEEN %s AND %s"
    values = (mini,maxi)
    cursor.execute(query,values)
    result=cursor.fetchall()
    if result:
        print("Employees with salary in given range")
        print("------------------------------------")
        for row in result:
            print("Name : ",row[0])
            print("Salary : ",row[1])
            print("Salary : ",row[2])
            print("Department : ",row[3])
            print("Email : ",row[4])
            print("-------------------------------")
    else:
        print("No employees in this salary range")
    cursor.close()

if __name__=="__main__":
    while True:
        print("Employee Management System")
        print("1.Add New Employee")
        print("2.Update Employee")
        print("3.Delete Employee")
        print("4.List all Employees")
        print("5.Sort Employees")
        print("6.Filter Employees")
        print("7.Exit\n")
        ch=int(input("Enter your choice : "))
        if ch==1:
            Id=int(input("Employee Id : "))
            exist=search(Id)
            if exist==True:
                print("Employee Id already exist!\n")
            else:
                name=input("Name : ")
                salary=float(input("Salary : "))
                department=input("Department : ")
                email=input("Email : ")
                add_Emp(Id,name,salary,department,email)
        elif ch==2:
            Id=input("Employee Id : ")
            exist=search(Id)
            if exist==True:
                cursor = mydb.cursor()
                query = "SELECT * FROM EMPLOYEE WHERE EMP_ID LIKE '%{}'".format(Id)
                cursor.execute(query)
                result=cursor.fetchall()
                if result:
                    for row in result:
                        print("Name : ",row[1])
                        print("Salary : ",row[2])
                        print("Department : ",row[3])
                        print("Email : ",row[4])
                        print("----------------------")
                cursor.close()
                name=input("Name : ")
                salary=float(input("Salary : "))
                department=input("Department : ")
                email=input("Email : ")
                update_Emp(Id,name,salary,department,email)
            else:
                print("Employee Id not exist!!!\n")
        elif ch==3:
            Id = int(input("Employee Id to be deleted : "))
            exist = search(Id)
            if exist==True:
                delete_Emp(Id)
            else:
                print("Employee Id not exist!!!\n")
        elif ch==4:
            listall()
        elif ch==5:
            print("\t1.Based on Department")
            print("\t2.Based on Salary")
            choice=int(input("Enter your choice : "))
            if choice==1:
                sortDept()
            elif choice==2:
                sortSalary()
            else:
                print("Invalid choice\n")
        elif ch==6:
            print("\t1.Based on Department")
            print("\t2.Based on Salary")
            choice=int(input("Enter your choice : "))
            if choice==1:
                dept=input("Enter the Department : ")
                filterDept(dept)
            elif choice==2:
                mini=float(input("Enter minimum salary range : "))
                maxi=float(input("Enter maximum salary range : "))
                filterSalary(mini,maxi)
            else:
                print("Invalid choice\n")
            
        elif ch==7:
            break
        else:
            print("Invalid choice\n")
    mydb.close()

Employee Management System
1.Add New Employee
2.Update Employee
3.Delete Employee
4.List all Employees
5.Sort Employees
6.Filter Employees
7.Exit

Enter your choice : 1
Employee Id : 5
Name : Rithu
Salary : 60000
Department : IT
Email : rithu@gmail.com
Success!!!

Employee Management System
1.Add New Employee
2.Update Employee
3.Delete Employee
4.List all Employees
5.Sort Employees
6.Filter Employees
7.Exit

Enter your choice : 4
Employee Details :
-------------------
Employee Id :  1
Employee Name :  John Doe
Salary :  50000.00
Department :  IT
Email :  SSS@gmail
---------------------
Employee Id :  2
Employee Name :  Joanna
Salary :  60000.00
Department :  HR
Email :  abc@gmail
---------------------
Employee Id :  3
Employee Name :  Ram
Salary :  30000.00
Department :  ER
Email :  ram@gmail.com
---------------------
Employee Id :  4
Employee Name :  Diya
Salary :  40000.00
Department :  IT
Email :  abc@gmail
---------------------
Employee Id :  5
Employee Name :  Rithu
Salary :  60000.00
Department :  IT
Email :  rithu@gmail.com
---------------------
Employee Management System
1.Add New Employee
2.Update Employee
3.Delete Employee
4.List all Employees
5.Sort Employees
6.Filter Employees
7.Exit

Enter your choice : 2
Employee Id : 3
Name :  Ram
Salary :  30000.00
Department :  ER
Email :  ram@gmail.com
----------------------
Name : Ram
Salary : 35000
Department : ER
Email : ram@gmail.com
Successfully Updated!!

Employee Management System
1.Add New Employee
2.Update Employee
3.Delete Employee
4.List all Employees
5.Sort Employees
6.Filter Employees
7.Exit

Enter your choice : 3
Employee Id to be deleted : 2
Deleted..
Employee Management System
1.Add New Employee
2.Update Employee
3.Delete Employee
4.List all Employees
5.Sort Employees
6.Filter Employees
7.Exit

Enter your choice : 4
Employee Details :
-------------------
Employee Id :  1
Employee Name :  John Doe
Salary :  50000.00
Department :  IT
Email :  SSS@gmail
---------------------
Employee Id :  3
Employee Name :  Ram
Salary :  35000.00
Department :  ER
Email :  ram@gmail.com
---------------------
Employee Id :  4
Employee Name :  Diya
Salary :  40000.00
Department :  IT
Email :  abc@gmail
---------------------
Employee Id :  5
Employee Name :  Rithu
Salary :  60000.00
Department :  IT
Email :  rithu@gmail.com
---------------------
Employee Management System
1.Add New Employee
2.Update Employee
3.Delete Employee
4.List all Employees
5.Sort Employees
6.Filter Employees
7.Exit

Enter your choice : 5
	1.Based on Department
	2.Based on Salary
Enter your choice : 2
Employee Details :
-------------------
Employee Id :  3
Employee Name :  Ram
Salary :  35000.00
Department :  ER
Email :  ram@gmail.com
---------------------
Employee Id :  4
Employee Name :  Diya
Salary :  40000.00
Department :  IT
Email :  abc@gmail
---------------------
Employee Id :  1
Employee Name :  John Doe
Salary :  50000.00
Department :  IT
Email :  SSS@gmail
---------------------
Employee Id :  5
Employee Name :  Rithu
Salary :  60000.00
Department :  IT
Email :  rithu@gmail.com
---------------------
Employee Management System
1.Add New Employee
2.Update Employee
3.Delete Employee
4.List all Employees
5.Sort Employees
6.Filter Employees
7.Exit

Enter your choice : 6
	1.Based on Department
	2.Based on Salary
Enter your choice : 1
Enter the Department : IT
Employee Details :
-------------------
Employee Id :  1
Employee Name :  John Doe
Salary :  50000.00
Department :  IT
Email :  SSS@gmail
---------------------
Employee Id :  4
Employee Name :  Diya
Salary :  40000.00
Department :  IT
Email :  abc@gmail
---------------------
Employee Id :  5
Employee Name :  Rithu
Salary :  60000.00
Department :  IT
Email :  rithu@gmail.com
---------------------
Employee Management System
1.Add New Employee
2.Update Employee
3.Delete Employee
4.List all Employees
5.Sort Employees
6.Filter Employees
7.Exit

Enter your choice : 7